# -*- coding: utf-8 -*-
"""Randomizador_participantes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aWM6HswxUR2K6cP-mk5oMl3TspuzT_2j

Para criar a randomização duplo cego do seu estudo, basta clicar no ícone de play no código a seguir.

NÃO É NECESSÁRIO SABER PROGRAMAR EM PYTHON! BASTA RODAR O CÓDIGO QUE AS INFORMAÇÕES IRÃO APARECER ABAIXO DO CÓDIGO E SEGUIR AS INSTRUÇÕES.


Abaixo do código irá aparecer algumas informações sobre o processo de randomização.
Quando o arquivo "estudo_randomizado.xlsx" for criado, basta clicar no ícone de pasta no menu à esquerda para encontrar o arquivo e fazer o download para seu computador.
O nome do arquivo criado é um nome genérico, é recomendado alterar esse nome quando salvar em seu computado para facilitar achar depois e caso esteja fazendo mais de um estudo.

OBS1. Caso você tenha alguma sugestão de aprimoramento do código é bem vindo para uma nova versão.

OBS2. Código gerado com o auxilio do Gemini.
"""

import pandas as pd
import numpy as np
import random as rd

n = int(input("digite o número total de participantes: "))
g = int(input("digite o número de grupos: "))

print("*************************************************")

estudo = pd.DataFrame({'ID': range(1, n + 1)})

print(f"Número total de participantes: {n}")
print(f"Número de grupos: {g}")

print("*************************************************")

base_per_group = n // g
remainder = n % g

group_assignments = []
for _ in range(g):
    group_assignments.append(base_per_group)

for i in range(remainder):
    group_assignments[i] += 1

print("Participantes por grupo:", group_assignments)

final_group_assignment = []
for group_id, count in enumerate(group_assignments):
    final_group_assignment.extend([group_id + 1] * count)

rd.shuffle(final_group_assignment)
estudo['GRUPO'] = final_group_assignment

print("\nContagem de participantes por grupo após randomização:")
print(estudo['GRUPO'].value_counts())

estudo.to_excel('estudo_randomizado.xlsx', index=False)

print("*************************************************")

print("DataFrame 'estudo' exportado com sucesso para 'estudo_randomizado.xlsx'")

print("*************************************************")

print("Clique no ícone de pasta no menu à esquerda para fazer o download do arquivo dos participantes randomizados por grupo .")

"""Obrigada por usar o Randomizador de participantes.
*************************************************

Qualquer sugestão ou dúvidas: marianna.cecyn@gmail.com

**Dra Marianna Cecyn**,

Neurocientista, Doutora em Ciências, Pesquisadora, Analista de Dados e Consultora Científica.

lattes: http://lattes.cnpq.br/6956271647156234

orcid: https://orcid.org/0000-0002-4995-7482

github: https://github.com/mariannacecyn
"""